### ISSUE TITLE
@rsbuild/core@0.5.0 compilation.hooks.processAssets.stageOptimizeHash is undefined

### ISSUE THREAD

**Issue by Magikarp-2020** [Clarkkkk/workbox-rspack-plugin#2]
when i use in @rsbuild/core@0.5.0, @Clarkkkk/workbox-rspack-plugin something abnormal happened

```
<e> [webpack-dev-middleware] [Error:   × TypeError: Cannot read properties of undefined (reading 'tapPromise')
<e>   │     at /node_modules/.pnpm/@aaroon+workbox-rspack-plugin@0.2.2_@rspack+core@0.5.9/node_modules/@aaroon/workbox-rspack-plugin/dist/index.cjs:259:47
<e>   │     at Hook.eval [as call] (eval at create (/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
<e>   │     at Hook.CALL_DELEGATE [as _call] (/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:14:14)
<e>   │     at Compiler._Compiler_newCompilation (/node_modules/.pnpm/@rspack+core@0.5.7_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/Compiler.js:862:32)
<e>   │ 
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

debug in code:

![image](https://github.com/Clarkkkk/workbox-rspack-plugin/assets/18202306/e2fd7029-f828-478d-be63-e172c206b34b)

find not has`stageOptimizeHash` method.

https://github.com/Clarkkkk/workbox-rspack-plugin/blob/main/src/inject-manifest.ts#L101

change code to:

```
compilation.hooks.processAssets.tapPromise(
```

everything runs fine

**Comment by Clarkkkk** [comment]
Thanks for reporting. The change was introduced by rspack 0.5.7 [#5861](https://github.com/web-infra-dev/rspack/pull/5861/commits/f75f6bae0a7a6b1d0dda4929cb6c75beafad63f9). Its behavior is aligned with webpack now.
